import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { api } from "../services/api";
const PAGE_SIZE=20,escapeRegExp=(value:string)=>value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
export function SessionIntelligence({sessionId,onLoaded}:{sessionId:string;onLoaded?:(data:{audio:any})=>void}){
 const onLoadedRef=useRef(onLoaded);useEffect(()=>{onLoadedRef.current=onLoaded});
 const[data,setData]=useState<any>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(0),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(""),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(""),[history,setHistory]=useState<any[]>([]);
 const load=()=>{Promise.all([api.get(`/v1/sessions/${sessionId}/audio`),api.get(`/v1/sessions/${sessionId}/transcript`),api.get(`/v1/sessions/${sessionId}/discourse`),api.get(`/v1/sessions/${sessionId}/content`),api.get(`/v1/sessions/${sessionId}/evidence-graph`)]).then(([audio,transcript,discourse,content,evidence])=>{setData({audio:audio.data,transcript:transcript.data,discourse:discourse.data,content:content.data,evidence:evidence.data});onLoadedRef.current?.({audio:audio.data})}).catch(()=>setError("Audio and transcript evidence could not be loaded."))};
 useEffect(load,[sessionId]);const filtered=useMemo(()=>(data?.transcript.segments||[]).filter((s:any)=>!query||s.text.toLowerCase().includes(query.toLowerCase())),[data,query]),visible=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
 function highlighted(value:string){if(!query)return value;return value.split(new RegExp(`(${escapeRegExp(query)})`,`ig`)).map((part,index)=>part.toLowerCase()===query.toLowerCase()?<mark key={index}>{part}</mark>:part)}
 function seek(seconds:number){const video=document.querySelector("video") as HTMLVideoElement|null;if(video){video.currentTime=seconds;void video.play().catch(()=>undefined)}}
 async function beginEdit(segment:any){setEditing(segment.id);setDraft(segment.text);setSaveError("");try{setHistory((await api.get(`/v1/transcript-segments/${segment.id}/corrections`)).data)}catch{setHistory([])}}
 async function save(event:FormEvent){event.preventDefault();if(!editing)return;setSaving(true);setSaveError("");try{await api.put(`/v1/transcript-segments/${editing}`,{corrected_text:draft});setEditing(null);load()}catch{setSaveError("Correction could not be saved. Your draft is preserved.")}finally{setSaving(false)}}
 if(error)return <section className="table-card" role="alert"><h2>Audio & lecture intelligence</h2><div className="empty">{error}</div><button onClick={()=>{setError("");load()}}>Retry</button></section>;
 if(!data)return <section className="table-card" aria-busy="true">Loading audio and lecture evidence…</section>;
 return <section className="table-card"><h2>Audio & lecture intelligence</h2><div className="notice">Optional anonymous research signals. No speaker identity is inferred and unavailable evidence is never synthesized.</div>
 <p><b>Audio:</b> {data.audio.status} · quality {data.audio.quality_status} · diarization {data.audio.diarization_status||"MODEL_DISABLED"}</p>{data.audio.limitations?.map((v:string)=><p className="empty" key={v}>{v}</p>)}<p><b>Discourse:</b> {data.discourse.status} · speaker roles default to UNKNOWN</p>
 <h3>Transcript</h3>{data.transcript.status==="RETENTION_DELETED"?<div className="empty">Transcript was removed by the configured retention policy.</div>:<><label>Search transcript <input aria-label="Search transcript" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label>{visible.map((s:any)=><article key={s.id} className="transcript-row"><button className="button secondary" onClick={()=>seek(s.start_seconds)} aria-label={`Jump to ${s.start_seconds} seconds`}>{s.start_seconds.toFixed(1)}–{s.end_seconds.toFixed(1)}s</button><small>{s.speaker_role} · {s.corrected?"Human corrected":"Machine generated"} · confidence {s.confidence??"Unavailable"}</small><p>{highlighted(s.text)}</p><button onClick={()=>beginEdit(s)}>Edit transcript</button>{editing===s.id&&<form onSubmit={save}><label>Correction<textarea aria-label="Correction" value={draft} onChange={e=>setDraft(e.target.value)}/></label><button disabled={saving}>{saving?"Saving…":"Save correction"}</button>{saveError&&<div role="alert">{saveError}</div>}<details><summary>Correction history ({history.length})</summary>{history.map(item=><p key={item.id}>{item.previous_text} → {item.corrected_text}</p>)}</details></form>}</article>)}{!visible.length&&<div className="empty">{query?"No transcript matches.":"No transcript evidence is available."}</div>}{filtered.length>PAGE_SIZE&&<div className="actions"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.ceil(filtered.length/PAGE_SIZE)}</span><button disabled={(page+1)*PAGE_SIZE>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div>}{data.transcript.status==="AVAILABLE"&&<div className="actions">{["json","csv","txt"].map(f=><a key={f} className="button secondary" href={`/api/v1/sessions/${sessionId}/transcript/export?format=${f}`}>Export {f.toUpperCase()}</a>)}</div>}</>}
 <h3>Grounded lecture content</h3><small>AI/deterministically generated from transcript evidence</small>{data.content.chapters?.map((c:any)=><p key={c.id}><b>{c.title}</b> · {c.start_seconds.toFixed(1)}–{c.end_seconds.toFixed(1)}s</p>)}{data.content.items?.slice(0,12).map((i:any)=><p key={i.id}><small>{i.type} · generated · confidence {i.confidence}</small><br/>{i.text}</p>)}{!data.content.items?.length&&<div className="empty">Transcript evidence is required; content was not generated.</div>}
 <h3>Explainable evidence fusion</h3><p><b>{data.evidence.value??"Unavailable"}</b> · confidence {data.evidence.confidence??"Unavailable"} · context {data.evidence.context||"Unavailable"} · method {data.evidence.methodology_version||"Not run"}</p>{data.evidence.nodes?.filter((n:any)=>n.type==="EVIDENCE").map((n:any)=><p key={n.id}>{n.id.replaceAll("_"," ")} · {n.included===false?<span>Excluded: {n.exclusion_reason}</span>:<span>Included · value {n.value} · effective weight {n.effective_weight}</span>}</p>)}{data.evidence.limitations?.map((v:string)=><div className="empty" key={v}>{v}</div>)}</section>
}
