// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from "@testing-library/react";import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";import {api} from "../services/api";import {SessionIntelligence} from "./SessionIntelligence";
vi.mock("../services/api",()=>({api:{get:vi.fn(),put:vi.fn()}}));const get=vi.mocked(api.get),put=vi.mocked(api.put);
const responses=()=>[{data:{status:"MODEL_DISABLED",quality_status:"UNAVAILABLE",diarization_status:"MODEL_DISABLED",limitations:["Audio disabled"]}},{data:{status:"AVAILABLE",segments:[{id:"one",start_seconds:1,end_seconds:3,text:"chlorophyll absorbs light",original_text:"chlorophyll absorbs lite",corrected:true,speaker_role:"UNKNOWN",confidence:.8}]}},{data:{status:"AVAILABLE"}},{data:{status:"AVAILABLE",chapters:[],items:[{id:1,type:"KEY_TERM",text:"chlorophyll",confidence:.6}]}},{data:{status:"AVAILABLE",value:64,confidence:.7,context:"LECTURE",methodology_version:"1.0",nodes:[{id:"visual_orientation",type:"EVIDENCE",included:true,value:70,effective_weight:.6},{id:"discourse_coverage",type:"EVIDENCE",included:false,exclusion_reason:"Reviewer excluded evidence"}],limitations:[]}}];
function success(){const values=responses();get.mockImplementation((url:string)=>url.includes("corrections")?Promise.resolve({data:[{id:1,previous_text:"lite",corrected_text:"light"}]} as any):Promise.resolve(values.shift()! as any))}beforeEach(()=>{vi.resetAllMocks();success()});
afterEach(cleanup);
describe("Session intelligence workflow",()=>{
it("renders states, labels, context and exclusions",async()=>{render(<SessionIntelligence sessionId="1"/>);expect(await screen.findByText((_,element)=>element?.tagName==="P"&&Boolean(element.textContent?.includes("Audio: MODEL_DISABLED")))).toBeTruthy();expect(screen.getByText(/AI\/deterministically generated/)).toBeTruthy();expect(screen.getByText(/context LECTURE/)).toBeTruthy();expect(screen.getByText(/Reviewer excluded evidence/)).toBeTruthy()});
it("searches and highlights",async()=>{render(<SessionIntelligence sessionId="1"/>);await screen.findByText("chlorophyll absorbs light");fireEvent.change(screen.getByLabelText("Search transcript"),{target:{value:"chlorophyll"}});expect(document.querySelector("mark")?.textContent).toBe("chlorophyll");fireEvent.change(screen.getByLabelText("Search transcript"),{target:{value:"missing"}});expect(screen.getByText("No transcript matches.")).toBeTruthy()});
it("loads history and preserves failed corrections",async()=>{put.mockRejectedValue(new Error("no"));render(<SessionIntelligence sessionId="1"/>);await screen.findByText("chlorophyll absorbs light");fireEvent.click(screen.getByText("Edit transcript"));await screen.findByText(/Correction history \(1\)/);fireEvent.change(screen.getByLabelText("Correction"),{target:{value:"corrected draft"}});fireEvent.click(screen.getByText("Save correction"));expect((await screen.findByRole("alert")).textContent).toContain("draft is preserved");expect((screen.getByLabelText("Correction") as HTMLTextAreaElement).value).toBe("corrected draft")});
it("renders retention and errors",async()=>{const values:any[]=responses();values[1]={data:{status:"RETENTION_DELETED",segments:[]}};get.mockImplementation(()=>Promise.resolve(values.shift()! as any));const view=render(<SessionIntelligence sessionId="1"/>);expect(await screen.findByText(/removed by the configured retention policy/)).toBeTruthy();view.unmount();get.mockRejectedValue(new Error("offline"));render(<SessionIntelligence sessionId="2"/>);expect((await screen.findByRole("alert")).textContent).toContain("could not be loaded")});
});
