"""Priority 3 audio, transcript, content, and evidence persistence."""
from alembic import op
import sqlalchemy as sa
revision="20260823_priority3"; down_revision="20260823_priority2_complete"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("audio_analyses",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("audio_path",sa.Text()),sa.Column("duration",sa.Float(),nullable=False),sa.Column("sample_rate",sa.Integer()),sa.Column("quality_status",sa.String(24),nullable=False),sa.Column("quality",sa.JSON(),nullable=False),sa.Column("coverage",sa.JSON(),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.Column("provider",sa.String(80)),sa.Column("model_version",sa.String(120)),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("session_id",name="uq_audio_analysis_session")); op.create_index("ix_audio_analyses_session_id","audio_analyses",["session_id"])
    op.create_table("transcript_segments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("start_seconds",sa.Float(),nullable=False),sa.Column("end_seconds",sa.Float(),nullable=False),sa.Column("original_text",sa.Text(),nullable=False),sa.Column("corrected_text",sa.Text()),sa.Column("confidence",sa.Float()),sa.Column("language",sa.String(20)),sa.Column("speaker_role",sa.String(24),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("model_version",sa.String(120)),sa.Column("generated",sa.Boolean(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.UniqueConstraint("session_id","start_seconds","end_seconds",name="uq_transcript_session_time")); op.create_index("ix_transcript_segments_session_id","transcript_segments",["session_id"]); op.create_index("ix_transcript_segments_start_seconds","transcript_segments",["start_seconds"])
    op.create_table("transcript_corrections",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("segment_id",sa.String(36),sa.ForeignKey("transcript_segments.id"),nullable=False),sa.Column("previous_text",sa.Text(),nullable=False),sa.Column("corrected_text",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_transcript_corrections_segment_id","transcript_corrections",["segment_id"])
    op.create_table("speaker_segments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("start_seconds",sa.Float(),nullable=False),sa.Column("end_seconds",sa.Float(),nullable=False),sa.Column("role",sa.String(24),nullable=False),sa.Column("confidence",sa.Float()),sa.UniqueConstraint("session_id","start_seconds","end_seconds",name="uq_speaker_session_time"))
    op.create_table("discourse_analyses",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.Column("model_version",sa.String(80),nullable=False),sa.UniqueConstraint("session_id",name="uq_discourse_session"))
    op.create_table("lecture_chapters",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("start_seconds",sa.Float(),nullable=False),sa.Column("end_seconds",sa.Float(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_segment_ids",sa.JSON(),nullable=False),sa.Column("generated",sa.Boolean(),nullable=False),sa.UniqueConstraint("session_id","start_seconds",name="uq_chapter_session_start"))
    op.create_table("generated_content_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("content_type",sa.String(40),nullable=False),sa.Column("ordinal",sa.Integer(),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("edited_text",sa.Text()),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("evidence_segment_ids",sa.JSON(),nullable=False),sa.Column("timestamps",sa.JSON(),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("generated",sa.Boolean(),nullable=False),sa.UniqueConstraint("session_id","content_type","ordinal",name="uq_content_session_type_order"))
    op.create_table("evidence_fusion_results",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id"),nullable=False),sa.Column("methodology_version",sa.String(40),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("value",sa.Float()),sa.Column("confidence",sa.Float()),sa.Column("coverage",sa.JSON(),nullable=False),sa.Column("components",sa.JSON(),nullable=False),sa.Column("limitations",sa.JSON(),nullable=False),sa.Column("weights",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("session_id","methodology_version",name="uq_fusion_session_version"))

def downgrade():
    for table in ("evidence_fusion_results","generated_content_items","lecture_chapters","discourse_analyses","speaker_segments","transcript_corrections","transcript_segments","audio_analyses"): op.drop_table(table)
