"""Priority 4 users, courses, alerts, notes, and ownership."""
from alembic import op
import sqlalchemy as sa
revision="20260823_priority4";down_revision="20260823_priority3";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("email",sa.String(255),nullable=False),sa.Column("display_name",sa.String(160),nullable=False),sa.Column("role",sa.String(24),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_users_email","users",["email"],unique=True)
 op.add_column("classrooms",sa.Column("description",sa.Text()));op.add_column("classrooms",sa.Column("location_label",sa.String(160)));op.add_column("classrooms",sa.Column("active",sa.Boolean(),server_default="1",nullable=False));op.add_column("classrooms",sa.Column("owner_user_id",sa.Integer()))
 op.create_index("ix_classrooms_owner_user_id","classrooms",["owner_user_id"])
 op.create_table("courses",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("code",sa.String(60),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("academic_term",sa.String(100)),sa.Column("classroom_id",sa.Integer(),sa.ForeignKey("classrooms.id")),sa.Column("owner_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_courses_code","courses",["code"]);op.create_index("ix_courses_classroom_id","courses",["classroom_id"]);op.create_index("ix_courses_owner_user_id","courses",["owner_user_id"])
 op.add_column("sessions",sa.Column("course_id",sa.Integer()))
 op.create_index("ix_sessions_course_id","sessions",["course_id"])
 op.create_table("course_memberships",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("course_id",sa.Integer(),sa.ForeignKey("courses.id"),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("membership_role",sa.String(24),nullable=False),sa.UniqueConstraint("course_id","user_id",name="uq_course_user"));op.create_index("ix_course_memberships_course_id","course_memberships",["course_id"]);op.create_index("ix_course_memberships_user_id","course_memberships",["user_id"])
 op.create_table("notifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("session_id",sa.Integer(),sa.ForeignKey("sessions.id")),sa.Column("category",sa.String(50),nullable=False),sa.Column("title",sa.String(180),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("dedupe_key",sa.String(180),nullable=False),sa.Column("read_at",sa.DateTime()),sa.Column("dismissed_at",sa.DateTime()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("user_id","dedupe_key",name="uq_notification_user_key"));op.create_index("ix_notifications_user_id","notifications",["user_id"]);op.create_index("ix_notifications_session_id","notifications",["session_id"]);op.create_index("ix_notifications_category","notifications",["category"])
 op.create_table("collaboration_notes",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("scope_type",sa.String(24),nullable=False),sa.Column("scope_id",sa.Integer(),nullable=False),sa.Column("author_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("body",sa.Text(),nullable=False),sa.Column("review_status",sa.String(24),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False));op.create_index("ix_collaboration_notes_scope_type","collaboration_notes",["scope_type"]);op.create_index("ix_collaboration_notes_scope_id","collaboration_notes",["scope_id"])
 op.create_table("audit_entries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("actor_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("action",sa.String(80),nullable=False),sa.Column("resource_type",sa.String(40),nullable=False),sa.Column("resource_id",sa.Integer()),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_audit_entries_actor_user_id","audit_entries",["actor_user_id"]);op.create_index("ix_audit_entries_action","audit_entries",["action"])
def downgrade():
 op.drop_table("audit_entries");op.drop_table("collaboration_notes");op.drop_table("notifications");op.drop_table("course_memberships");op.drop_index("ix_sessions_course_id",table_name="sessions");
 with op.batch_alter_table("sessions") as b:b.drop_column("course_id")
 op.drop_table("courses");op.drop_index("ix_classrooms_owner_user_id",table_name="classrooms")
 with op.batch_alter_table("classrooms") as b:b.drop_column("owner_user_id");b.drop_column("active");b.drop_column("location_label");b.drop_column("description")
 op.drop_table("users")
