/* eslint-disable react-hooks/set-state-in-effect -- initial and polling loads intentionally synchronize remote API state */
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../services/api';
const colors=['#62d9ff','#a78bfa','#31d8a0','#fb7185'];
const percent=(v:number|null|undefined)=>v==null?'Unavailable':`${Math.round(v*100)}%`;
export function AnalyticsWorkspacePage(){
 const[ids,setIds]=useState(''),[comparison,setComparison]=useState<any>(null),[trends,setTrends]=useState<any>(null),[notifications,setNotifications]=useState<any[]>([]),[classrooms,setClassrooms]=useState<any[]>([]),[courses,setCourses]=useState<any[]>([]);
 const[period,setPeriod]=useState('weekly'),[metric,setMetric]=useState('observable_participation'),[classroom,setClassroom]=useState(''),[course,setCourse]=useState(''),[activity,setActivity]=useState(''),[source,setSource]=useState('REAL'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[category,setCategory]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notificationPage,setNotificationPage]=useState(1);
 async function load(){setLoading(true);setError('');try{const params={period,metric,data_source:source,classroom_id:classroom||undefined,course_id:course||undefined,activity_context:activity||undefined,start_date:start||undefined,end_date:end||undefined};const[a,b]=await Promise.all([api.get('/v1/analytics/trends',{params}),api.get('/v1/notifications',{params:{category:category||undefined}})]);setTrends(a.data);setNotifications(b.data);setNotificationPage(1)}catch(e:any){setError(e.response?.data?.detail||'Trend evidence could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{Promise.all([api.get('/v1/classrooms'),api.get('/v1/courses')]).then(([a,b])=>{setClassrooms(Array.isArray(a.data)?a.data:[]);setCourses(Array.isArray(b.data)?b.data:[])}).catch(()=>{});void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 async function compare(e:FormEvent){e.preventDefault();const parsed=ids.split(',').map(x=>x.trim()).filter(Boolean);if(parsed.some(x=>!/^\d+$/.test(x))||new Set(parsed).size<2){setMessage('Enter at least two distinct numeric session IDs.');return}try{setComparison((await api.post('/v1/analytics/compare',{session_ids:parsed.map(Number),metrics:[metric]})).data);setMessage('')}catch(e:any){setMessage(e.response?.data?.detail||'Comparison could not be loaded.')}}
 async function createNote(e:FormEvent){e.preventDefault();await api.post('/v1/notes',{scope_type:'SESSION',scope_id:Number(ids.split(',')[0]),body:note});setNote('');setMessage('Note saved with version history.')}
 async function act(id:number,kind:'read'|'dismiss'){await api.post(`/v1/notifications/${id}/${kind}`);setNotifications(rows=>rows.filter(row=>row.id!==id))}
 const series=useMemo(()=>Array.from(new Set((trends?.points||[]).map((p:any)=>p.series))) as string[],[trends]);const chartData=useMemo(()=>{const grouped=new Map<string,any>();for(const point of trends?.points||[]){const row=grouped.get(point.bucket)||{bucket:point.bucket};row[point.series]=point.value;grouped.set(point.bucket,row)}return Array.from(grouped.values())},[trends]);const visible=notifications.slice((notificationPage-1)*8,notificationPage*8);
 return <><div className="page-head"><div><h1>Compare & Trends</h1><p>Filtered anonymous evidence; real sessions are selected by default.</p></div></div>{message&&<div className="notice">{message}</div>}{error&&<div className="notice error">{error}</div>}<section className="table-card"><h2>Trend filters</h2><div className="filters"><select aria-label="Metric" value={metric} onChange={e=>setMetric(e.target.value)}>{[['observable_participation','Observable participation'],['visual_orientation','Visual orientation'],['possible_fatigue','Possible fatigue'],['occupancy','Occupancy'],['camera_quality','Camera quality']].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select aria-label="Classroom" value={classroom} onChange={e=>setClassroom(e.target.value)}><option value="">All classrooms</option>{classrooms.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="Course" value={course} onChange={e=>setCourse(e.target.value)}><option value="">All courses</option>{courses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><select aria-label="Activity type" value={activity} onChange={e=>setActivity(e.target.value)}><option value="">All activities</option>{['LECTURE','GROUP_DISCUSSION','PRESENTATION','EXAM','OTHER'].map(x=><option key={x}>{x.replaceAll('_',' ')}</option>)}</select><select aria-label="Trend period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><select aria-label="Data source" value={source} onChange={e=>setSource(e.target.value)}><option value="REAL">Real only</option><option value="DEMO">Demo/test only</option><option value="ALL">All data</option></select><input aria-label="Start date" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input aria-label="End date" type="date" value={end} onChange={e=>setEnd(e.target.value)}/><button onClick={()=>void load()} disabled={loading}>{loading?'Loading…':'Apply filters'}</button></div>{loading?<div className="state">Loading filtered evidence…</div>:chartData.length?<><h3>{metric.replaceAll('_',' ')}</h3><ResponsiveContainer width="100%" height={300}><LineChart data={chartData}><XAxis dataKey="bucket"/><YAxis domain={[0,100]}/><Tooltip/><Legend/>{series.map((name,index)=><Line key={name} connectNulls={false} dataKey={name} stroke={colors[index%colors.length]}/>)}</LineChart></ResponsiveContainer>{trends.points.map((p:any)=><p key={`${p.bucket}-${p.series}-${p.methodology_version}`}><b>{p.bucket}</b> · {p.series.replaceAll('_',' ')} · {p.value??`Insufficient evidence — ${p.reason}`} · {p.contributing_sessions}/{p.session_count} valid · coverage {percent(p.coverage)} · confidence {percent(p.confidence)}</p>)}</>:<div className="empty">No valid evidence exists for these filters.</div>}</section>
 <section className="table-card"><h2>Session comparison</h2><form onSubmit={compare}><label>Session IDs (comma separated)<input aria-label="Session IDs" value={ids} onChange={e=>setIds(e.target.value)}/></label><button>Compare evidence</button></form>{comparison?.warnings?.map((w:string)=><div className="notice" key={w}>{w}</div>)}{comparison?.sessions?.map((row:any)=><p key={row.session_id}><b>{row.name}</b> · {row.context} · {row.metrics?.[metric]??'Unavailable'} · coverage {percent(row.coverage)} · confidence {percent(row.confidence)}</p>)}</section><div className="detail-layout"><section className="table-card"><h2>Advisory notifications</h2><select aria-label="Notification category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{['POOR_CAMERA','POOR_AUDIO','MODEL_PROVIDER_UNAVAILABLE','INSUFFICIENT_EVIDENCE','PROCESSING_FAILED'].map(x=><option key={x}>{x}</option>)}</select>{visible.length?visible.map(n=><article key={n.id}><b>{n.title}</b><p>{n.message}</p><button onClick={()=>void act(n.id,'read')}>Mark read</button><button onClick={()=>void act(n.id,'dismiss')}>Dismiss</button></article>):<div className="empty">No active notifications.</div>}<div className="actions"><button disabled={notificationPage===1} onClick={()=>setNotificationPage(x=>x-1)}>Previous</button><button disabled={notificationPage*8>=notifications.length} onClick={()=>setNotificationPage(x=>x+1)}>Next</button></div></section><section className="table-card"><h2>Collaboration note</h2><form onSubmit={createNote}><textarea aria-label="Session note" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={!note||!ids}>Save note</button></form></section></div></>
}
