import { Camera, Radio, Square } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import { api } from '../services/api';
import type { Session } from '../types';

export function LivePage(){
  const[sessions,setSessions]=useState<Session[]>([]);const[selected,setSelected]=useState('');const[live,setLive]=useState<any>(null);const[events,setEvents]=useState<any[]>([]);const[running,setRunning]=useState(false);const[error,setError]=useState('');
  const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const socketRef=useRef<WebSocket|null>(null);const timerRef=useRef<number|null>(null);const streamRef=useRef<MediaStream|null>(null);
  useEffect(()=>{api.get('/sessions').then(r=>setSessions(r.data))},[]);
  useEffect(()=>{if(!selected||running)return;const scheme=location.protocol==='https:'?'wss':'ws';const socket=new WebSocket(`${scheme}://${location.hostname}:8000/ws/sessions/${selected}`);socket.onmessage=e=>{const data=JSON.parse(e.data);setLive(data);if(data.analytics)setEvents(old=>[data.analytics,...old].slice(0,20))};return()=>socket.close()},[selected,running]);
  async function startCamera(){try{setError('');const created=await api.post('/sessions',{name:`Live classroom ${new Date().toLocaleString()}`,source_type:'LIVE'});const id=String(created.data.id);setSelected(id);setSessions(old=>[created.data,...old]);const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}const scheme=location.protocol==='https:'?'wss':'ws';const socket=new WebSocket(`${scheme}://${location.hostname}:8000/ws/live/${id}`);socketRef.current=socket;socket.onopen=()=>{setRunning(true);timerRef.current=window.setInterval(()=>sendFrame(socket),500)};socket.onmessage=e=>{const data=JSON.parse(e.data);if(data.error){setError(data.error);return}setLive({analytics:data,stage:'LIVE_ANALYSIS',processing_speed:data.processing_fps});setEvents(old=>[data,...old].slice(0,20))};socket.onerror=()=>setError('Live analysis connection failed.');}catch(e:any){setError(e.response?.data?.detail||e.message||'Camera unavailable')}}
  function sendFrame(socket:WebSocket){const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||socket.readyState!==WebSocket.OPEN||!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d')?.drawImage(video,0,0);canvas.toBlob(blob=>blob?.arrayBuffer().then(buffer=>socket.send(buffer)),'image/jpeg',.72)}
  async function stop(){if(timerRef.current)clearInterval(timerRef.current);socketRef.current?.close();streamRef.current?.getTracks().forEach(track=>track.stop());if(selected)await api.post(`/sessions/${selected}/stop`);setRunning(false)}
  return <><div className="page-head"><div><h1>Live classroom</h1><p>Real browser-camera inference with anonymous tracking</p></div><span className="live-dot">● {running?'LIVE ANALYSIS':'READY'}</span></div><div className="live-controls"><select value={selected} disabled={running} onChange={e=>setSelected(e.target.value)}><option value="">Select a processed session</option>{sessions.map(row=><option value={row.id} key={row.id}>{row.name} · {row.status}</option>)}</select>{running?<button onClick={stop}><Square size={17}/>Stop analysis</button>:<button onClick={startCamera}><Camera size={17}/>Start webcam analysis</button>}</div>{error&&<div className="notice error">{error}</div>}<div className="live-layout"><section className="video-panel"><video ref={videoRef} muted playsInline controls={!running} src={!running&&selected?`/api/sessions/${selected}/video?annotated=true`:undefined}/>{running&&live?.analytics?.annotated_image&&<img className="live-overlay" src={`data:image/jpeg;base64,${live.analytics.annotated_image}`}/>}<canvas ref={canvasRef} hidden/>{!selected&&!running&&<div className="video-empty"><Radio size={38}/><b>Start a live session</b><span>Camera frames are processed without storing face crops.</span></div>}</section><section className="live-metrics">{[['Students','student_count'],['Visual attention','attention'],['Engagement','engagement'],['Possible drowsiness','drowsiness'],['Fatigue','fatigue'],['Yawning','yawning'],['Raised hands','raised_hands'],['Empty seats','empty_seats']].map(([label,key])=><article key={key}><small>{label}</small><b>{live?.analytics?.[key]??'—'}</b></article>)}<div className="progress"><span>{live?.stage||'NO SESSION'} · {live?.processing_speed??0} FPS · {live?.analytics?.latency_ms??live?.latency_ms??0}ms</span></div></section></div><section className="table-card timeline"><h2>Live timeline</h2>{events.length?events.map((row,index)=><p key={index}><time>{row.timestamp}s</time> Students {row.student_count} · Attention {row.attention??0}% · Raised hands {row.raised_hands??0}</p>):<div className="empty">Live events will appear here.</div>}</section></>
}
