import { CloudUpload, Film, RotateCcw } from 'lucide-react';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
export function UploadPage(){
 const[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[uploadProgress,setUploadProgress]=useState(0),[job,setJob]=useState<any>(null);const timer=useRef<number|null>(null);
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);
 function monitor(jobId:string){if(timer.current)clearInterval(timer.current);const poll=async()=>{try{const next=(await api.get(`/jobs/${jobId}`)).data;setJob(next);if(['COMPLETED','FAILED','CANCELLED'].includes(next.status)&&timer.current){clearInterval(timer.current);timer.current=null}}catch{setMessage('Processing status could not be refreshed.')}};void poll();timer.current=window.setInterval(poll,1500)}
 async function submit(e:FormEvent){e.preventDefault();if(!file)return;setBusy(true);setMessage('Uploading…');setJob(null);const data=new FormData();data.append('file',file);data.append('name',file.name);try{const response=await api.post('/uploads',data,{onUploadProgress:event=>setUploadProgress(event.total?Math.round(event.loaded/event.total*100):0)});setMessage(`Session #${response.data.id} queued for real analysis.`);setJob({job_id:response.data.job_id,session_id:response.data.id,status:'QUEUED',stage:'QUEUED',progress:0,processed_frames:0,total_frames:response.data.total_frames});monitor(response.data.job_id)}catch(error:any){setMessage(error.response?.data?.detail||'Upload failed.')}finally{setBusy(false)}}
 async function retry(){if(!job?.job_id)return;await api.post(`/jobs/${job.job_id}/retry`);setMessage('Processing retry queued.');monitor(job.job_id)}
 return <><div className="page-head"><div><h1>Process a classroom video</h1><p>Validated MP4, AVI, MOV, or MKV · asynchronous real analytics</p></div></div><form className="upload-card" onSubmit={submit}><label className="drop"><CloudUpload size={42}/><b>{file?file.name:'Drop a classroom recording here'}</b><span>or click to browse</span><input type="file" accept="video/mp4,video/quicktime,video/x-msvideo,video/x-matroska,.mp4,.avi,.mov,.mkv" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={!file||busy}><Film size={18}/>{busy?`Uploading ${uploadProgress}%`:'Upload and queue analysis'}</button>{busy&&<div className="progress"><span>UPLOADING</span><b>{uploadProgress}%</b><i style={{width:`${uploadProgress}%`}}/></div>}{message&&<div className="notice">{message}</div>}{job&&<section className="table-card"><h2>Processing job</h2><p><b>{job.stage||job.status}</b> · {job.progress??0}%</p><div className="progress"><span>{job.processed_frames??0} / {job.total_frames??0} frames</span><b>{job.processing_speed??0} FPS</b><i style={{width:`${job.progress??0}%`}}/></div>{job.error&&<div className="notice error">{job.error} {job.failure_code&&`(${job.failure_code})`}</div>}<div className="actions">{job.status==='FAILED'&&<button type="button" onClick={()=>void retry()}><RotateCcw size={15}/>Retry processing</button>}<Link to={`/sessions/${job.session_id}`}>View session</Link>{job.report_ready&&<Link to="/reports">View completed report</Link>}</div></section>}</form></>
}
